export enum ThemePreference {
  AI_CHOOSE = "ai_choose",
  LIGHT = "light",
  DARK = "dark",
  CREATIVE_GALLERY = "creative_gallery",
  TECH_SAAS = "tech_saas",
  EDITORIAL_LUXURY = "editorial_luxury",
  APPLE_CLEAN = "apple_clean",
  BRUTALIST_STREET = "brutalist_street",
  CREATIVE_NEON_NOIR = "creative_neon_noir",
  MINIMALIST_JAPANDI = "minimalist_japandi",
  ORGANIC_ECO = "organic_eco",
  RETRO_BAUHAUS = "retro_bauhaus",
  CYBER_TERMINAL = "cyber_terminal"
}

export interface ClientMatrixInput {
  companyName: string;
  sector: string; // Free-form input
  companyEmail: string; // Required E-Mail field
  companyAddress: string; // Required Address field
  pageType: "single-page" | "multi-page"; // Required Page structure choice
  servicesSummary: string;
  targetAudience: string;
  contactPhone: string;
  whatsappMessage: string;
  googleMapsReviewsUrl?: string;
  logoUrl?: string; // Data URL or external link
  heroStyle: "bold-minimalist" | "split-image" | "neo-brutalist" | "centered-elegant" | "glassmorphism-glow" | "apple-minimalist" | "futuristic-dashboard" | "interactive-slider" | "full-slider-video" | "ai-choose";
  servicesStyle: "hover-accent-border" | "bento-box" | "neon-glassmorphism" | "editorial-grid" | "apple-list" | "interactive-tabs" | "ai-choose";
  features: {
    whatsappBtn: boolean;
    leadForm: boolean;
    newsletter: boolean;
    testimonialCarousel: boolean;
    faqSection: boolean;
    popupBanner: boolean;
    webpCompression: boolean;
    // Extended Component Library configurations (Dynamic choices)
    whatsappIntegrationType?: "standard-bubble" | "floating-chat" | "footer-cta" | "ai-choose";
    popupType?: "discount-coupon" | "newsletter-signup" | "emergency-notice" | "ai-choose";
    galleryLayout?: "grid-masonry" | "justified-bento" | "stacked-mosaic" | "creative-neon-glow" | "cyber-darkroom" | "disabled" | "ai-choose";
    blogTemplate?: "editorial-cards" | "detailed-list" | "disabled" | "ai-choose";
    ecommerceCatalog?: "mini-products" | "services-grid" | "disabled" | "ai-choose";
    showGmapsReviews?: boolean;
  };
  theme: ThemePreference;
}

export interface ServiceItem {
  title: string;
  description: string;
  iconName: string; // lucide icon identifier e.g., "Activity", "Briefcase", "Utensils", etc.
  conversionHook: string; // Conversion booster message for this service
  imageUrl?: string; // Rich context Unsplash image URL
}

export interface BlogPost {
  title: string;
  summary: string;
  date: string;
  readTime: string;
  imageUrl: string;
  author: string;
}

export interface ProductItem {
  id: string;
  title: string;
  price: string;
  originalPrice?: string;
  description: string;
  imageUrl: string;
}

export interface GalleryItem {
  imageUrl: string;
  title: string;
  description: string;
  category: string;
}

export interface GoogleReview {
  authorName: string;
  rating: number;
  text: string;
  relativeTime: string;
  avatarUrl?: string;
}

export interface GeneratedWebsite {
  companyName: string;
  sector: string;
  companyEmail: string; // Added Required Email field
  companyAddress: string; // Added Required Address field
  pageType: "single-page" | "multi-page"; // Added Page structure choice
  tagline: string;
  heroHeadline: string;
  heroSubheadline: string;
  heroCtaText: string;
  aboutText: string;
  services: ServiceItem[];
  uvpTexts: string[]; // Unique Value Propositions
  faqList: { question: string; answer: string; }[];
  testimonials: { clientName: string; feedback: string; rating: number; role: string; }[];
  popupContent?: { title: string; subtitle: string; cta: string; couponCode?: string; type: "discount-coupon" | "newsletter-signup" | "emergency-notice"; };
  contactPrompt: string;
  contactPhone: string;
  whatsappMessage: string;
  
  // Custom inputs integrated by AI / system
  googleMapsReviewsUrl?: string;
  logoUrl?: string;
  heroStyle: "bold-minimalist" | "split-image" | "neo-brutalist" | "centered-elegant" | "glassmorphism-glow" | "apple-minimalist" | "futuristic-dashboard" | "interactive-slider" | "full-slider-video";
  servicesStyle: "hover-accent-border" | "bento-box" | "neon-glassmorphism" | "editorial-grid" | "apple-list" | "interactive-tabs";
  resolvedUnsplashHeroUrl: string;

  // Integrated library outputs
  blogPosts?: BlogPost[];
  ecommerceProducts?: ProductItem[];
  galleryList?: GalleryItem[];
  googleReviews?: GoogleReview[];
  resolvedWhatsappType: "standard-bubble" | "floating-chat" | "footer-cta";

  // Design system generated by Gemini (autonomous decision)
  design: {
    primaryColor: string; // hex
    secondaryColor: string; // hex
    backgroundColor: string; // hex
    textColor: string; // hex
    fontFamilyHeading: string; // e.g., 'Space Grotesk', 'Playfair Display', 'Outfit'
    fontFamilyBody: string; // 'Inter', 'Lora', etc.
    fontPairingVibe: string; // Turkish description of selected design mood
    layoutStructure: "Bento" | "Classic" | "Minimalist" | "SaaS Grid" | "Apple Fluid" | "Glassmorphic Glow" | "Chic Gallery" | "Bold Retro";
  };

  // Senior SEO layer outputs (fully customized)
  seo: {
    metaTitle: string;
    metaDescription: string;
    metaKeywords: string[];
    structuredDataJson: string; // JSON-LD payload string
    sitemapXml: string; // customized sitemap string representation
    robotsTxt: string; // custom robots.txt
    webpOptimizations: { filename: string; originalSize: string; webpSize: string; reduction: string; altText: string; }[];
    errorContent404: { heading: string; body: string; recoveryCta: string; };
  };

  // AI Selection Logic Reasoning Logs so user can see autonomous processing
  aiOrchestratorLogs: {
    role: "UX Analyst" | "SEO Specialist" | "Creative Director" | "Copywriter" | "Developer Team";
    message: string;
    timestamp: string;
  }[];

  theme?: ThemePreference;
  features?: ClientMatrixInput["features"];
}
